
---
- name: "Get zabbix repo"
  get_url: 
    url: "{{ zabbix_Repository }}"
    dest: /tmp
- shell: dpkg -i /tmp/"{{ zabbix_file }}"

- name: "Install zabbix-server"
  apt: 
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - zabbix-server-mysql
    - zabbix-frontend-php  

# Settings for database
- name: "Create a new database"
  shell: echo "create database {{ DBUser }} character set utf8 collate utf8_bin;" | mysql

- name: "Grant privileges"
  shell: echo "grant all privileges on {{ DBName }}.* to zabbix@localhost identified by '{{ DBPassword }}';" | mysql

- name: "Importing schema file"
  shell: mysql -u{{ DBUser }} -p{{ DBPassword }} {{ DBName }} -e "show tables;" | wc -l
  register: zabbixDatabaseTables
  changed_when: False

- name: "Zcat 'create.sql.gz' | Import 'schema.sql, 'images.sql', 'data.sql'"
  shell: zcat /usr/share/doc/zabbix-server-mysql/create.sql.gz | mysql -u"{{ DBUser }}" -p"{{ DBPassword }}" "{{ DBName }}"
  when: zabbixDatabaseTables|int == 0

- name: "Setting zabbix_server.conf"
  lineinfile:
    dest: '/etc/zabbix/zabbix_server.conf'
    regexp: "{{ item.regexp }}"
    insertafter: "{{ item.insertafter }}"
    line: "{{ item.line }}"
  with_items:
    - regexp: '^DBHost='
      insertafter: "^# DBHost="
      line: 'DBHost={{ DBHost }}'
    - regexp: '^DBName='
      insertafter: "^# DBName="
      line: 'DBName={{ DBName }}'
    - regexp: '^DBUser='
      insertafter: "^# DBUser="
      line: 'DBUser={{ DBUser }}'
    - regexp: '^DBPassword='
      insertafter: "^# DBPassword="
      line: 'DBPassword={{ DBPassword }}'
  notify: 
    - restart zabbix-server

