---
- name: "Installing repository rpm"
  get_url:
    url: "{{ percona_Repository }}"
    dest: /tmp
- shell: dpkg -i /tmp/"{{ percona_file }}"

- name: "Install MySQL"
  apt: 
    name: "{{ item }}"
    state: present
    update_cache: yes  
  with_items:
    - percona-server-server-5.7
  
- name: "Start Myql and enabled"
  service: 
    name: "{{ mysql_service }}"
    state: "{{ mysql_service_state }}"
    enabled: "{{ mysql_service_enabled }}"

