
---
- name: "Installing repository rpm"
  get_url:
    url: "{{ percona_Repository }}"
    dest: /tmp
- shell: dpkg -i /tmp/"{{ percona_file }}"

- name: "Install MySQL"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - percona-server-server-5.6


- name: "Get zabbix repo"
  get_url: 
    url: "{{ zabbix_Repository }}"
    dest: /tmp
- shell: dpkg -i /tmp/"{{ zabbix_file }}"

- name: "Install zabbix-server"
  apt: 
    name: "{{ item }}"
    #enablerepo: zabbix
    state: present
  with_items:
    - zabbix-server-mysql
    - zabbix-frontend-php  

# Settings for database
- name: "Create a new database"
  shell: echo "create database {{ DBUser }} character set utf8 collate utf8_bin;" | mysql

- name: "Grant privileges"
  shell: echo "grant all privileges on {{ DBName }}.* to zabbix@localhost identified by '{{ DBPassword }}';" | mysql

- name: "Importing schema file"
  shell: mysql -u{{ DBUser }} -p{{ DBPassword }} {{ DBName }} -e "show tables;" | wc -l
  register: zabbixDatabaseTables
  changed_when: False

- name: "Zcat 'create.sql.gz' | Import 'schema.sql, 'images.sql', 'data.sql'"
  shell: zcat /usr/share/doc/zabbix-server-mysql/create.sql.gz | mysql -u"{{ DBUser }}" -p"{{ DBPassword }}" "{{ DBName }}"
  when: zabbixDatabaseTables|int == 0

#- name: "Copy PHP-files for Frontend zabbix-web"
#  shell: cp -R /usr/share/zabbix/ /var/www/html/

- name: "Setting zabbix_server.conf"
  lineinfile:
    dest: '/etc/zabbix/zabbix_server.conf'
    regexp: "{{ item.regexp }}"
    insertafter: "{{ item.insertafter }}"
    line: "{{ item.line }}"
  with_items:
    - regexp: '^ListenPort='
      insertafter: "^# ListenPort="
      line: 'ListenPort={{ ListenPort }}'
    - regexp: '^LogFile='
      insertafter: "^# LogFile="
      line: 'LogFile={{ LogFile }}'
    - regexp: '^DBHost='
      insertafter: "^# DBHost="
      line: 'DBHost={{ DBHost }}'
    - regexp: '^DBName='
      insertafter: "^# DBName="
      line: 'DBName={{ DBName }}'
    - regexp: '^DBUser='
      insertafter: "^# DBUser="
      line: 'DBUser={{ DBUser }}'
    - regexp: '^DBPassword='
      insertafter: "^# DBPassword="
      line: 'DBPassword={{ DBPassword }}'
#    - regexp: '^DBPort='
#      insertafter: "^# DBPort="
#      line: 'DBPort={{ DBPort }}'
#    - regexp: '^DBSocket='
#      insertafter: "^# DBSocket="
#      line: 'DBSocket={{ DBSocket }}'
  notify: 
    - restart zabbix-server

